<?php
echo "GLOBALS";
echo "<br />";
echo "<br />";
print_r($GLOBALS);
echo "<br />";
echo "<br />";
echo "SERVER";
echo "<br />";
echo "<br />";
print_r($_SERVER);
echo "<br />";
echo "<br />";
echo "GET";
echo "<br />";
echo "<br />";
print_r($_GET);
echo "<br />";
echo "<br />";
echo "POST";
echo "<br />";
echo "<br />";
print_r($_POST);
echo "<br />";
echo "<br />";
echo "FILES";
echo "<br />";
echo "<br />";
print_r($_FILES);
echo "<br />";
echo "<br />";
echo "COOKIE";
echo "<br />";
echo "<br />";
print_r($_COOKIE);
echo "<br />";
echo "<br />";
echo "SESSION";
echo "<br />";
echo "<br />";
print_r($_SESSION);
echo "<br />";
echo "<br />";
echo "REQUEST";
echo "<br />";
echo "<br />";
print_r($_REQUEST);
echo "<br />";
echo "<br />";
print_r($_ENV);

?>